---
layout: post
title: 使用async function处理异步逻辑
categories: javascript
tags:
  - es6
  - babel
  - webpack
---


在有复杂异步场景下，特别是多个异步串行执行时，可考虑直接使用es7的async/await。  
使用[babel](http://babeljs.io/)的话需要开启[preset stage-3](http://babeljs.io/docs/plugins/preset-stage-3/)及以上才支持。

我使用的是webpack，相关配置如下：


```js
module: {
  loaders: [
    {
      test: /\.js$/,

      exclude: function(path) {
        return !!path.match(/\/node_modules\//);
      },

      loaders: [
        {
          loader: 'babel-loader',
          query: {
            presets: ['react', 'es2015', 'stage-0'],
            cacheDirectory: true
          }
        }
      ]
    }
  ]
  ...
```

以上配置可以让webpack正常编译`async function`和`es6 generator function`。运行时还需要添加 [regenerator-runtime](https://github.com/facebook/regenerator/tree/master/packages/regenerator-runtime)。

安装：

```
npm install --save regenerator-runtime
```

然后将它在入口中载入：


```js
import 'regenerator-runtime/runtime';
```

## 异常处理

使用try/catch是可以直接捕获异常的。


```js
async takeCoupon() {
  try {
    const res = await ajax({...});
    ...
  } catch(e) {
    return { success: false };
  }
}
```

以上`ajax`期望返回的是一个`Promise`对象。 但是使用异常语句控制正常逻辑不是很好，我们可以使用`Promise#catch`。

``` js
async takeCoupon() {
  const res = await ajax({...})
    .catch(e => {
      ...
      return { success: false };
    });
}
```
